### ISSUE TITLE
Merge-Issues-Fixes

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-frontend#105]
- registration-form: address-street still contains disabled - must be removed, because fieldset handles that for us
- registration-form: change needConfirmationObs to needConfirmation$

- registration-form: minor script exception while interacting with card and setSelectionRange on number HTMElement does not support selection.

- Trader List: Town is gone
- Trader List: slider breakpoint is not correct

- debug outputs must be reduced throughout the application

**Comment by lukaesch** [comment]
- registration-form: address-street still contains disabled - must be removed, because fieldset handles that for us: OK

- registration-form: change needConfirmationObs to needConfirmation$: OK

- registration-form: minor script exception while interacting with card and setSelectionRange on number HTMElement does not support selection. OK

- Trader List: Town is gone: OK

- Trader List: slider breakpoint is not correct: OK

- debug outputs must be reduced throughout the application: OK
