### ISSUE TITLE
Products: Pricing field does not recognize RegEx.

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-frontend#182]
You can give 
* negative values
* extremely high values
* single chars that are no digis

**Comment by Dipanjana1990** [comment]
Here below written are the points that  I observed. The fields seem to behave all right. 
@christianaschoff :But in order to be sure I would like to know if these are the expected result
Less than 1 and more than 10000 are not accepted, 
Negative values are not accepted
Only one character which is not digit is accepted which turns later automatically into "€"

![image](https://user-images.githubusercontent.com/68644410/117703424-ec8ae300-b1c9-11eb-84cb-c2d5145a7c9a.png)

**Comment by christianaschoff** [comment]
@Dipanjana1990 sounds good to me

**Comment by Dipanjana1990** [comment]
Shifted to "Done"
